steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "ROOT_URL=${_ROOT_URL}"
      - "AWS_S3_ACCESS_KEY_ID=${_AWS_S3_ACCESS_KEY_ID}"
      - "AWS_S3_SECRET_ACCESS_KEY=${_AWS_S3_SECRET_ACCESS_KEY}"
      - "AWS_S3_BUCKET_NAME=${_AWS_S3_BUCKET_NAME}"
  - name: node:10.15.1
    entrypoint: npm
    args: ["bundle"]
  - name: "gcr.io/cloud-builders/gcloud"
    # args: ["app", "deploy",'app.yaml', '--project', 'shareit-part2-pro']
    args: ["app", "deploy", "--project", "share-it-front-prod"]
