steps:
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["create-env"]
    env:
      - "ROOT_URL=${_ROOT_URL}"
      - "AWS_S3_ACCESS_KEY_ID=${_AWS_S3_ACCESS_KEY_ID}"
      - "AWS_S3_SECRET_ACCESS_KEY=${_AWS_S3_SECRET_ACCESS_KEY}"
      - "AWS_S3_BUCKET_NAME=${_AWS_S3_BUCKET_NAME}"
  - name: "gcr.io/cloud-builders/yarn"
    args: ["debug1"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["debug2"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["debug3"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["bundle"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--project", "share-it-front-prod"]
